/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;


import java.awt.*;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import  java.io.ObjectInputStream;
import java.io.FileInputStream;
import java.util.Objects;
import javax.swing.JOptionPane;

public class addbooks extends javax.swing.JFrame {

    /**
     * Creates new form addandremovebooks
     */

    Data d =new  Data();

    public addbooks() {
        initComponents();
        d.data();
        
        Dimension screenSize, frameSize;
        int x, y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize = getSize();
        x = (screenSize.width - frameSize.width) / 2;
        y = (screenSize.height - frameSize.height) / 2;
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        bookidtextfrild = new javax.swing.JTextField();
        bookidlable = new javax.swing.JLabel();
        booktitletextfeild = new javax.swing.JTextField();
        booktitlelable = new javax.swing.JLabel();
        authortextfeild = new javax.swing.JTextField();
        authorlable = new javax.swing.JLabel();
        publishertextfeild = new javax.swing.JTextField();
        publisherlable = new javax.swing.JLabel();
        yeartextfeild = new javax.swing.JTextField();
        yearofpublicationlable = new javax.swing.JLabel();
        isbntextfeild = new javax.swing.JTextField();
        isnlable = new javax.swing.JLabel();
        copiestextfeild = new javax.swing.JTextField();
        numberofcopieslable = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        showdatalable = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD BOOK");
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        bookidtextfrild.setBackground(new java.awt.Color(0, 51, 51));
        bookidtextfrild.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bookidtextfrild.setForeground(new java.awt.Color(255, 255, 255));
        bookidtextfrild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookidtextfrildActionPerformed(evt);
            }
        });

        bookidlable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        bookidlable.setForeground(new java.awt.Color(255, 255, 255));
        bookidlable.setText("Book ID");

        booktitletextfeild.setBackground(new java.awt.Color(0, 51, 51));
        booktitletextfeild.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        booktitletextfeild.setForeground(new java.awt.Color(255, 255, 255));
        booktitletextfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booktitletextfeildActionPerformed(evt);
            }
        });

        booktitlelable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        booktitlelable.setForeground(new java.awt.Color(255, 255, 255));
        booktitlelable.setText("Book Title");

        authortextfeild.setBackground(new java.awt.Color(0, 51, 51));
        authortextfeild.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        authortextfeild.setForeground(new java.awt.Color(255, 255, 255));
        authortextfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authortextfeildActionPerformed(evt);
            }
        });

        authorlable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        authorlable.setForeground(new java.awt.Color(255, 255, 255));
        authorlable.setText("Author");

        publishertextfeild.setBackground(new java.awt.Color(0, 51, 51));
        publishertextfeild.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        publishertextfeild.setForeground(new java.awt.Color(255, 255, 255));
        publishertextfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishertextfeildActionPerformed(evt);
            }
        });

        publisherlable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        publisherlable.setForeground(new java.awt.Color(255, 255, 255));
        publisherlable.setText("Publisher");

        yeartextfeild.setBackground(new java.awt.Color(0, 51, 51));
        yeartextfeild.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        yeartextfeild.setForeground(new java.awt.Color(255, 255, 255));
        yeartextfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeartextfeildActionPerformed(evt);
            }
        });

        yearofpublicationlable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        yearofpublicationlable.setForeground(new java.awt.Color(255, 255, 255));
        yearofpublicationlable.setText("Year Of Publication");

        isbntextfeild.setBackground(new java.awt.Color(0, 51, 51));
        isbntextfeild.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        isbntextfeild.setForeground(new java.awt.Color(255, 255, 255));
        isbntextfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbntextfeildActionPerformed(evt);
            }
        });

        isnlable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        isnlable.setForeground(new java.awt.Color(255, 255, 255));
        isnlable.setText("ISBN");

        copiestextfeild.setBackground(new java.awt.Color(0, 51, 51));
        copiestextfeild.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        copiestextfeild.setForeground(new java.awt.Color(255, 255, 255));

        numberofcopieslable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        numberofcopieslable.setForeground(new java.awt.Color(255, 255, 255));
        numberofcopieslable.setText("Numbers Of Copies");

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/left-arrow.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(0, 51, 51));
        exit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        clearbutton.setBackground(new java.awt.Color(0, 51, 51));
        clearbutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(255, 255, 255));
        clearbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/broom.png"))); // NOI18N
        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        addbutton.setBackground(new java.awt.Color(0, 51, 51));
        addbutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addbutton.setForeground(new java.awt.Color(255, 255, 255));
        addbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/add.png"))); // NOI18N
        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        showdatalable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        showdatalable.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(showdatalable, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(clearbutton)
                            .addGap(18, 18, 18)
                            .addComponent(exit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addbutton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(isnlable)
                                            .addGap(54, 54, 54))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(authorlable, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(booktitlelable)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(5, 5, 5)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(publisherlable)
                                                            .addComponent(bookidlable)))))
                                            .addGap(30, 30, 30))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(numberofcopieslable)
                                        .addComponent(yearofpublicationlable))
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(copiestextfeild)
                                .addComponent(isbntextfeild)
                                .addComponent(yeartextfeild)
                                .addComponent(publishertextfeild, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(authortextfeild, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(booktitletextfeild, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bookidtextfrild, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showdatalable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookidtextfrild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookidlable, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(booktitlelable, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booktitletextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authortextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorlable, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publishertextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publisherlable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearofpublicationlable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yeartextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isnlable)
                    .addComponent(isbntextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberofcopieslable)
                    .addComponent(copiestextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearbutton)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbutton))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
    if (d.file.isFile()) {
        memeber selectedBook = null;
        try {
            // Validate Book ID (Integer)
            int bookId;
            try {
                bookId = Integer.parseInt(bookidtextfrild.getText());
            } catch (NumberFormatException ex) {
                showdatalable.setText("Book ID must be an integer.");
                return;
            }

            // Validate Author (String)
            String author = authortextfeild.getText();
            if (author.isEmpty() || !author.matches("^[a-zA-Z ]+$")) {
                showdatalable.setText("Author must be in alphabets.");
                return;
            }

            // Validate Publisher (String)
            String publisher = publishertextfeild.getText();
            if (publisher.isEmpty()|| !publisher.matches("^[a-zA-Z ]+$") ) {
                showdatalable.setText("Publisher must be in alphabets.");
                return;
            }
            

            // Validate Year of Publication (Date Format: MM/dd/yyyy)
            String yearOfPublication = yeartextfeild.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
            dateFormat.setLenient(false); // Strict parsing
            try {
                Date date = dateFormat.parse(yearOfPublication);
            } catch (ParseException ex) {
                showdatalable.setText("Year of Publication must be in MM/dd/yyyy format.");
                return;
            }

            // Validate ISBN (13-digit Integer)
            String isbn = isbntextfeild.getText();
            if (!isbn.matches("^\\d{13}$")) {
                showdatalable.setText("ISBN must be a 13-digit number.");
                return;
            }

            // Validate Number of Copies (Integer)
            int numberOfCopies;
            try {
                numberOfCopies = Integer.parseInt(copiestextfeild.getText());
            } catch (NumberFormatException ex) {
                showdatalable.setText("Number of Copies must be an integer.");
                return;
            }

            // All validations passed, add the book
             memeber newBook = new memeber(String.valueOf(bookId), booktitletextfeild.getText(), author, publisher, yearOfPublication, isbn, String.valueOf(numberOfCopies));
            d.a.add(newBook);
            d.oos = new ObjectOutputStream(new FileOutputStream(d.file));
            d.oos.writeObject(d.a);
            d.oos.close();
            JOptionPane.showMessageDialog(this,"Book added successfully");

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,"Error try again");
        }
    }
    }//GEN-LAST:event_addbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:n
        management obj1 = new management();
        obj1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        bookidtextfrild.setText("");
        booktitletextfeild.setText("");
        authortextfeild.setText("");
        publishertextfeild.setText("");
        yeartextfeild.setText("");
        isbntextfeild.setText("");
        copiestextfeild.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void bookidtextfrildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookidtextfrildActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bookidtextfrildActionPerformed

    private void booktitletextfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booktitletextfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booktitletextfeildActionPerformed

    private void isbntextfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbntextfeildActionPerformed
        // TODO add your han code hdlingere:
    }//GEN-LAST:event_isbntextfeildActionPerformed

    private void authortextfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authortextfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authortextfeildActionPerformed

    private void publishertextfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishertextfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publishertextfeildActionPerformed

    private void yeartextfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeartextfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yeartextfeildActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addbooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JLabel authorlable;
    private javax.swing.JTextField authortextfeild;
    private javax.swing.JLabel bookidlable;
    private javax.swing.JTextField bookidtextfrild;
    private javax.swing.JLabel booktitlelable;
    private javax.swing.JTextField booktitletextfeild;
    private javax.swing.JButton clearbutton;
    private javax.swing.JTextField copiestextfeild;
    private javax.swing.JButton exit;
    private javax.swing.JTextField isbntextfeild;
    private javax.swing.JLabel isnlable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel numberofcopieslable;
    private javax.swing.JLabel publisherlable;
    private javax.swing.JTextField publishertextfeild;
    private javax.swing.JLabel showdatalable;
    private javax.swing.JLabel yearofpublicationlable;
    private javax.swing.JTextField yeartextfeild;
    // End of variables declaration//GEN-END:variables
}
