/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.ListIterator;
import java.util.Objects;
import javax.swing.JOptionPane;


public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    Data d = new Data();
    ObjectInputStream objectInputStream = null;
    ObjectOutputStream objectOutputStream = null;
    ArrayList<memeber> userBooks = new ArrayList();

    public search() {
        initComponents();
        
        d.data();
         Dimension screenSize, frameSize;
        int x, y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize = getSize();
        x = (screenSize.width - frameSize.width) / 2;
        y = (screenSize.height - frameSize.height) / 2;
        setLocation(x, y);
    
        bookstextfeild.setText("BOOK ID" + "\t" + "BOOK TITLE" + "\t" + "AUTHOR" + "\t" + "PUBLISHER" + "\t" + "YEAR OF PUBLICATION" + "\t" + "ISBN" );
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bookstextfeild = new javax.swing.JTextField();
        backbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        seachtextfeild = new javax.swing.JTextField();
        takebookbutton = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookstextarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        bookstextfeild.setBackground(new java.awt.Color(0, 51, 51));
        bookstextfeild.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bookstextfeild.setForeground(new java.awt.Color(255, 255, 255));
        bookstextfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookstextfeildActionPerformed(evt);
            }
        });

        backbutton.setBackground(new java.awt.Color(0, 51, 51));
        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/left-arrow.png"))); // NOI18N
        backbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/loupe.png"))); // NOI18N
        jLabel1.setText("Search");

        seachtextfeild.setBackground(new java.awt.Color(0, 51, 51));
        seachtextfeild.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        seachtextfeild.setForeground(new java.awt.Color(255, 255, 255));
        seachtextfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seachtextfeildActionPerformed(evt);
            }
        });
        seachtextfeild.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                seachtextfeildKeyReleased(evt);
            }
        });

        takebookbutton.setBackground(new java.awt.Color(0, 51, 51));
        takebookbutton.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        takebookbutton.setForeground(new java.awt.Color(255, 255, 255));
        takebookbutton.setText("Take Book");
        takebookbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        takebookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takebookbuttonActionPerformed(evt);
            }
        });

        bookstextarea.setBackground(new java.awt.Color(0, 51, 51));
        bookstextarea.setColumns(20);
        bookstextarea.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bookstextarea.setForeground(new java.awt.Color(255, 255, 255));
        bookstextarea.setRows(5);
        jScrollPane1.setViewportView(bookstextarea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 340, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seachtextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(takebookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(bookstextfeild)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(takebookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(seachtextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(bookstextfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seachtextfeildKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seachtextfeildKeyReleased
        // TODO add your handling code here:
        boolean found = false;
        if (d.file.isFile()) {
            ListIterator li = d.a.listIterator();
            while (li.hasNext()) {

                memeber e = (memeber) li.next();
                if (seachtextfeild.getText().equalsIgnoreCase(e.bookid)) {
                    try {
                        bookstextarea.setText(e.bookid + "\t" + e.booktitle + "\t" + e.author + "\t" + e.publisher + "\t" + e.yearofpublication + "\t\t" + e.isbn );
                        found = true;
                    } catch (Exception i) {
                    }

                }

            }
        }
        if (seachtextfeild.getText().isEmpty()) {
            bookstextarea.setText("");
            return;
        }
        if (!found) {
            bookstextarea.setText("\t\t\t\tnot found");
        }
    }//GEN-LAST:event_seachtextfeildKeyReleased

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        new usermanagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void takebookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takebookbuttonActionPerformed
    
        
        
        String selectedBooktitle = seachtextfeild.getText(); // Assuming you have the selected book ID
    
    // Check if the book ID is valid and exists
    boolean found = false;
    memeber selectedBook = null;
    ListIterator<memeber> li = d.a.listIterator();
    while (li.hasNext()) {
        memeber e = li.next();
        if (selectedBooktitle.equalsIgnoreCase(e.bookid)) {
            selectedBook = e;
            found = true;
            break;
        }
    }
    
    if (!found) {
        bookstextarea.setText("Book not found.");
        return;
    }

    //                                                                      Save selected Book into Cart
        saveTakenBookInLoggedInUserFile(selectedBook);



    }//GEN-LAST:event_takebookbuttonActionPerformed

    private void bookstextfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookstextfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookstextfeildActionPerformed

    private void seachtextfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seachtextfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seachtextfeildActionPerformed

    public void saveTakenBookInLoggedInUserFile(memeber selectedBook){

        if(Objects.nonNull(usersloginpage.LoggedInUserFullName)) {
            File userFile = new File(usersloginpage.LoggedInUserFullName.concat(".txt"));
            if (userFile.isFile()) {
                // first we will fetch all existing books of current useP from his file and then we will add new book into it.
                userBooks = fetchExistingUserBooks(userFile);

                // now add taken book into current user file
                addCurrentBookInCurrentUserFile(userFile, userBooks, selectedBook);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Please Login Again to do any process");
        }

    }

    public ArrayList<memeber> fetchExistingUserBooks(File userFile){
        ArrayList<memeber> existingBooks = new ArrayList<>();
        try{
            objectInputStream = new ObjectInputStream(new FileInputStream(userFile));
            existingBooks = (ArrayList<memeber>) objectInputStream.readObject();
            objectInputStream.close();
        }catch (Exception e){

        }
        return existingBooks;
    }


    public void addCurrentBookInCurrentUserFile(File userFile,ArrayList<memeber> userBooks,memeber selectedBook){
        try{

            userBooks.add(selectedBook);
            objectOutputStream = new ObjectOutputStream(new FileOutputStream(userFile));
            objectOutputStream.writeObject(userBooks);
            objectOutputStream.close();


            // fetch books from data.txt // update quantity of selected book
            for (memeber book:d.a) {
                if(book.bookid.equalsIgnoreCase(selectedBook.bookid)){
                    int updateNoOfCopies = Integer.parseInt(book.noofcopies);
                    updateNoOfCopies-=1;
                    book.noofcopies = String.valueOf(updateNoOfCopies);
                }
            }

            // save books in data.txt

            d.oos = new ObjectOutputStream(new FileOutputStream(d.file));
            d.oos.writeObject(d.a);
            d.oos.close();

            bookstextarea.setText("Book taken successfully.");
        }catch (IOException e){
            bookstextarea.setText("Error taking the book: " + e.getMessage());
        }
    }
                                                                                // remove book from the user file
    public void returnBook(memeber returnedBook){
        boolean isBookDeleted = false;

        if(Objects.nonNull(usersloginpage.LoggedInUserFullName)) {
            File userFile = new File(usersloginpage.LoggedInUserFullName.concat(".txt"));
            ArrayList<memeber> existingUserBooks = fetchExistingUserBooks(userFile);


            isBookDeleted = existingUserBooks.removeIf(book -> book.bookid.equalsIgnoreCase(returnedBook.bookid));


            if(isBookDeleted){
                System.out.println("Book Successfully Removed");
            }
            else{
                System.out.println("Issue Removing Book");
            }

            try {
                objectOutputStream = new ObjectOutputStream(new FileOutputStream(userFile));
                objectOutputStream.writeObject(existingUserBooks);
                objectOutputStream.close();

                // fetch books from data.txt // increment quantity of returned book

                for (memeber book:d.a) {
                    if(book.bookid.equalsIgnoreCase(returnedBook.bookid)){
                        int updateNoOfCopies = Integer.parseInt(book.noofcopies);
                        updateNoOfCopies+=1;
                        book.noofcopies = String.valueOf(updateNoOfCopies);
                    }
                }

                d.oos = new ObjectOutputStream(new FileOutputStream(d.file));
                d.oos.writeObject(d.a);
                d.oos.close();

            } catch (Exception e) {

            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JTextArea bookstextarea;
    private javax.swing.JTextField bookstextfeild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField seachtextfeild;
    private javax.swing.JToggleButton takebookbutton;
    // End of variables declaration//GEN-END:variables
}
