/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


public class userrigistration extends javax.swing.JFrame {

    Registration d=new Registration();
    public userrigistration() {
        initComponents();
        
          Dimension screenSize, frameSize;
        int x, y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize = getSize();
        x = (screenSize.width - frameSize.width) / 2;
        y = (screenSize.height - frameSize.height) / 2;
        setLocation(x, y);
        d.registration();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        fristnamelable = new javax.swing.JLabel();
        lastnamelable = new javax.swing.JLabel();
        usernamelable = new javax.swing.JLabel();
        passwordlable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JToggleButton();
        backbutton = new javax.swing.JToggleButton();
        firstnametextfield = new javax.swing.JTextField();
        lastnametextfield = new javax.swing.JTextField();
        usernametextfield = new javax.swing.JTextField();
        showdatalable = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JPasswordField();
        CHECK = new javax.swing.JCheckBox();
        CHECK1 = new javax.swing.JCheckBox();

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD USER");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        fristnamelable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        fristnamelable.setForeground(new java.awt.Color(255, 255, 255));
        fristnamelable.setText("FRIST NAME");

        lastnamelable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lastnamelable.setForeground(new java.awt.Color(255, 255, 255));
        lastnamelable.setText("LAST NAME");

        usernamelable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        usernamelable.setForeground(new java.awt.Color(255, 255, 255));
        usernamelable.setText("USERNAME");

        passwordlable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        passwordlable.setForeground(new java.awt.Color(255, 255, 255));
        passwordlable.setText("PASSWORD");

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONFIRM PASSWORD");

        savebutton.setBackground(new java.awt.Color(0, 51, 51));
        savebutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        savebutton.setForeground(new java.awt.Color(255, 255, 255));
        savebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/login.png"))); // NOI18N
        savebutton.setText("SUBMIT");
        savebutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        clearbutton.setBackground(new java.awt.Color(0, 51, 51));
        clearbutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(255, 255, 255));
        clearbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/reload.png"))); // NOI18N
        clearbutton.setText("CLEAR");
        clearbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        backbutton.setBackground(new java.awt.Color(0, 51, 51));
        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/left-arrow.png"))); // NOI18N
        backbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        firstnametextfield.setBackground(new java.awt.Color(0, 51, 51));
        firstnametextfield.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        firstnametextfield.setForeground(new java.awt.Color(255, 255, 255));

        lastnametextfield.setBackground(new java.awt.Color(0, 51, 51));
        lastnametextfield.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lastnametextfield.setForeground(new java.awt.Color(255, 255, 255));

        usernametextfield.setBackground(new java.awt.Color(0, 51, 51));
        usernametextfield.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        usernametextfield.setForeground(new java.awt.Color(255, 255, 255));
        usernametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametextfieldActionPerformed(evt);
            }
        });

        showdatalable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        showdatalable.setForeground(new java.awt.Color(255, 0, 0));

        Password.setBackground(new java.awt.Color(0, 51, 51));
        Password.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));

        ConfirmPassword.setBackground(new java.awt.Color(0, 51, 51));
        ConfirmPassword.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordActionPerformed(evt);
            }
        });

        CHECK.setBackground(new java.awt.Color(0, 102, 102));
        CHECK.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CHECK.setForeground(new java.awt.Color(255, 255, 255));
        CHECK.setText("SHOW PASSWORD");
        CHECK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKActionPerformed(evt);
            }
        });

        CHECK1.setBackground(new java.awt.Color(0, 102, 102));
        CHECK1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CHECK1.setForeground(new java.awt.Color(255, 255, 255));
        CHECK1.setText("SHOW PASSWORD");
        CHECK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECK1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fristnamelable)
                                .addComponent(lastnamelable))
                            .addGap(43, 43, 43)
                            .addComponent(firstnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(usernamelable)
                                        .addComponent(passwordlable))
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(usernametextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastnametextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CHECK, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(100, 100, 100)
                                    .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(showdatalable, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CHECK1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(showdatalable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fristnamelable))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnamelable))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamelable))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlable)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CHECK)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CHECK1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametextfieldActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        if (d.file.isFile()) {
        try {
            
            // Validate First Name (String)
            String firstName = firstnametextfield.getText();
            if (firstName.isEmpty() || !firstName.matches("^[a-zA-Z]+$")) {
                showdatalable.setText("First name must be in alphabets.");
                return;
            }

            // Validate Last Name (String)
            String lastName = lastnametextfield.getText();
            if (lastName.isEmpty() || !lastName.matches("^[a-zA-Z]+$")) {
                showdatalable.setText("Last name must be alphabets.");
                return;
            }

            // Validate Username (String, at least 5 characters)
            String username = usernametextfield.getText();
            if (username.length() < 5) {
                showdatalable.setText("Username must be at least 5 characters long.");
                return;
            }

            // Validate Password (at least 8 characters, one special character, one numerical digit, one alphabet)
            String password = Password.getText();
            if (!password.matches("^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[@#$%^&+=!])(?=\\S+$).{8,}$")) {
                showdatalable.setText("Password must be at least 8 characters long and contain at least one special character, one numerical digit, and one alphabet.");
                return;
            }

            // Validate Confirm Password
            String confirmPassword = ConfirmPassword.getText();
            if (!password.equals(confirmPassword)) {
                showdatalable.setText("Passwords do not match.");
                return;
            }

            // Check if username is unique
            for (user existinguser : d.a) {
                if (existinguser.username.equals(username)) {
                    showdatalable.setText("Username is already taken.");
                    return;
                }
            }

            // Continue with your existing book-related validations...

            // All validations passed, add the book
            d.a.add(new user(firstName, lastName, username, password, confirmPassword));
            d.oos = new ObjectOutputStream(new FileOutputStream(d.file));
            d.oos.writeObject(d.a);
            d.oos.close();
           
            String filename = usernametextfield.getText() + ".txt"; // Make sure to get username from the text field
            File userFile = new File(filename);
            if (userFile.createNewFile()) {
                JOptionPane.showMessageDialog(this,"USER added successfully");
                this.dispose();
            } else {
                showdatalable.setText("Username file already exists.");
            }
        } catch (IOException e) {
            
        }
    }
    }//GEN-LAST:event_savebuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        new management().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        firstnametextfield.setText("");
        lastnametextfield.setText("");
        usernametextfield.setText("");
        Password.setText("");
        ConfirmPassword.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordActionPerformed

    private void CHECKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKActionPerformed
        // TODO add your handling code here:
         if (CHECK.isSelected()) {
            Password.setEchoChar((char)0);
        }
        else{
            Password.setEchoChar('*');
        }

    }//GEN-LAST:event_CHECKActionPerformed

    private void CHECK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECK1ActionPerformed
        // TODO add your handling code here:
         if (CHECK1.isSelected()) {
            ConfirmPassword.setEchoChar((char)0);
        }
        else{
            ConfirmPassword.setEchoChar('*');
        }

    }//GEN-LAST:event_CHECK1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userrigistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userrigistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userrigistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userrigistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userrigistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CHECK;
    private javax.swing.JCheckBox CHECK1;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JPasswordField Password;
    private javax.swing.JToggleButton backbutton;
    private javax.swing.JToggleButton clearbutton;
    private javax.swing.JTextField firstnametextfield;
    private javax.swing.JLabel fristnamelable;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lastnamelable;
    private javax.swing.JTextField lastnametextfield;
    private javax.swing.JLabel passwordlable;
    private javax.swing.JButton savebutton;
    private javax.swing.JLabel showdatalable;
    private javax.swing.JLabel usernamelable;
    private javax.swing.JTextField usernametextfield;
    // End of variables declaration//GEN-END:variables
}
